### ISSUE TITLE
Does this drive work with ESP301 controller using USB communication?

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-motor/motorNewport#12]
Does this driver work with ESP301 controller using its USB port?
There are two ports on ESP301:
A serial port at Baud 19200, 8N1
A direct USB port, Baud 921600, 8N1.
The USB connection is  much faster.

**Comment by kmpeters** [comment]
If the controller looks like a serial port to the OS, the EPICS support should work over USB.  I don't have an ESP301 I can use to test this.

**Comment by LeeYangLBLBCS** [comment]
The USB port doesn't show up as a tty when plugged in.
Does that mean it's not a serial port?
I used:
dmesg|grep tty 
to check it.

**Comment by kmpeters** [comment]
What does ``ls -l /dev/ttyUSB*`` show?

**Comment by LeeYangLBLBCS** [comment]
It showed no difference.

**Comment by kmpeters** [comment]
Can you share the dmesg output from when the EPS301 is connected?

**Comment by LeeYangLBLBCS** [comment]
this is the output of dmesg after I plugged in the USB cable.
[dmesg_usb.txt](https://github.com/epics-motor/motorNewport/files/9031644/dmesg_usb.txt)

**Comment by prjemian** [comment]
Similar info is obtained from `lsusb`, agree?

Is there an FTDI driver available (and udev rule that will automatically create serial port when the USB is plugged in)?

**Comment by prjemian** [comment]
Perhaps `/dev/ttyUSB*`?  Also `tail /var/log/syslog` just after you plug in the USB, which might be near identical to dmesg output.

**Comment by prjemian** [comment]
Instead of `tail, try `grep -i usb /var/log/syslog`

**Comment by LeeYangLBLBCS** [comment]
ftdi USB to serial dongle works.
After I reseated two of them, I got this:
dmesg|grep tty
[102155.790900] ftdi_sio ttyUSB1: FTDI USB Serial Device converter now disconnected from ttyUSB1
[102166.285620] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[102169.196397] usb 1-1.2: FTDI USB Serial Device converter now attached to ttyUSB0
[102173.278018] usb 1-1.1: FTDI USB Serial Device converter now attached to ttyUSB1
I remember ESP301 requires a USB driver on Windows OS in order to use the USB port.
I think it will need a similar driver for Linux.

**Comment by kmpeters** [comment]
Linux should support FTDI USB devices.  It is likely that the idVendor=104d & idProduct=3001 combo isn't known.  If you create and install a udev rule for the ESP301, it might work.  The procedure is similar to what is described in the DXP documentation, specifically the bullet point that starts with "USB devices on Linux":

https://millenia.cars.aps.anl.gov/software/epics/dxpDoc.html#Installing_Linux

**Comment by LeeYangLBLBCS** [comment]
thanks for the information.
I'll see if I can figure out how to write a udev rule.

**Comment by kmpeters** [comment]
If a driver is required on Windows, my deleted suggestion that maybe a udev rule would help is likely a bad suggestion.  You will probably need a USB driver, similar to the one on Windows.
