### ISSUE TITLE
XY group in Newport XPS 

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-motor/motorNewport#16]
Does XPS driver support XY group stage, where two motors are configured to move at the same time?
Some of our entrance/exit slits move better that way.
thanks.

**Comment by MarkRivers** [comment]
The XPS driver currently supports PVT groups, not XY groups.  PVT groups are the most general, and an XY group is effectively a subset.  The EPICS driver for the XPS supports several things for PVT groups:

- Deferred moves: All motors in the group are told where to go, and then they are all told to move at the same time.
- Profile moves: An array of target positions for each motor is sent to the controller.  The XPS is then told to execute the profile.  This allows multi-axis non-linear coordinated motion, which is called a trajectory scan in XPS terminology.  It can also put out trigger pulses along the trajector, and record the position of each encoder when the pulse was output.

**Comment by LeeYangLBLBCS** [comment]
thanks for the information.
