### ISSUE TITLE
Is it possible to change "private" access modifier to "protected" for XPSController and XPSAxis classes?

### ISSUE THREAD

**Issue by hovanes-egiyan** [epics-motor/motorNewport#21]
Hi, 

in order to implemented a custom referencing procedure for one of our motor applications at Jefferson Lab, we wrote a new class that inherits from the XPSController and XPSAxis classes and implements the functionalities that we need. But to do that we have to change the access modifiers "private" in XPSController and XPSAxis classes for the data members in the motorNewort source code before building our EPICS support modules and our code that uses motor record. Would it be possible to change those access modifiers in the newportMotor repository so that we do not have to modify the source code each time when we build for newer version of EPICS base or motor record? 

Thanks, 
  Hovanes Egiyan

**Comment by MarkRivers** [comment]
This has been done in commits https://github.com/epics-motor/motorNewport/commit/3fb05a1ae4f1e6cdf55cc1d2e9f0bc11ce177f73 and https://github.com/epics-motor/motorNewport/commit/a21852b22ca3bc65ea54a4d1cc02c88182869a47

**Comment by hovanes-egiyan** [comment]
Thanks!
