### ISSUE TITLE
Transform record support

### ISSUE THREAD

**Issue by domitto** [epics-motor/motorNewport#4]
Hi,
I'm trying to use the iocs/NewportIOC example but I'm getting **$(P)$(R)_tweak** is of an unknown type **transform** from the **XPSAuxAo.db** file. 
I tried to grep for **calcSupport.dbd** or **transformRecord.dbd** in the motor module but I couldn't find it being included anywhere.  Is it somehow being included indirectly or are we missing an include?

**Comment by MarkRivers** [comment]
The transform record comes from the calc module, but the motor module does not have calc as a dependency. “Real” applications need to have calc as a dependency.
