### ISSUE TITLE
what does motor PV's *_able" do?

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-motor/motorNewport#8]
ESP300 IOC comes up with PVs with the following names:
newport:m21_able
newport:m22_able
newport:m23_able
I can toggle them to Enable/Disable but they don't disable motors on the controller.
What are they supposed to do?
Is it a configuration issue in my st.cmd?
I also can't find the information in the EPICS  motor record documentation for this field.
thanks for the help.

**Comment by kmpeters** [comment]
The *_able records give users an easy way to set the DISP field which allows caputs to the motor fields other than DISP to be disabled:

https://github.com/epics-modules/motor/blob/cc6c6a9b181691e8b04981c64ec99f8a887a937e/motorApp/Db/motor.db#L28-L34

The DISP field is one of the fields common to all record types.  It is documented in EPICS base.  It appears on this page from the the old 3.14 record reference manual:

https://wiki-ext.aps.anl.gov/epics/index.php?title=RRM_3-14_dbCommon

**Comment by anjohnson** [comment]
Why not just write directly to the `.DISP` fields? They are explicitly excluded from the write protection that they provide when set.

@kmpeters There are much newer versions of the Record Reference manual pages, please don't link to the old Wiki version:
+ https://epics.anl.gov/base/R3-15/9-docs/dbCommonRecord.html
+ https://epics.anl.gov/base/R7-0/6-docs/dbCommonRecord.html

**Comment by prjemian** [comment]
This support (for enable) has existed since the 1990s. It provides for a
single button in a GUI screen to enable/disable a group of motors. Similar
synApps support is provided for groups of calcouts, swaits, and various
other records.

To answer the question "why", I believe the reason is to make it easier for
the beam line user.

**Comment by LeeYangLBLBCS** [comment]
why those "_able" records only exist in some epics motor IOCs?
For example, I see them in ESP300, but not in newport XPS and Aerotech Automation1 IOCs.

**Comment by kmpeters** [comment]
@anjohnson, thanks for the newer links.

@LeeYangLBLBCS, substitutions files that load basic_motor.db or basic_asyn_motor.db will not have the *_able records.  motor.db and asyn_motor.db do include the *_able records.
